[versions]
kotlin = "2.2.20"
compose = "1.8.2"
normalize = "1.2.0"
room = "2.8.0"
sqlite = "2.6.0"
kermit = "2.0.8"
cmptoast = "1.0.7"
compose_ui = "1.9.1"
test_runner = "1.7.0"
test_junit_ext = "1.3.0"
ksp = "2.2.10-2.0.2"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose_ui" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
normalize = { module = "com.doist.x:normalize", version.ref = "normalize" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
cmptoast = { module = "network.chaintech:cmptoast", version.ref = "cmptoast" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test_runner" }
androidx-test-core = { module = "androidx.test:core", version.ref = "test_runner" }
androidx-test-junit-ext = { module = "androidx.test.ext:junit", version.ref = "test_junit_ext" }
androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }