[versions]
ankiAndroid = "api-v1.1.0"
camerak-imagesaver = "0.0.7"
datastorePreferences = "1.1.7"
filekitCore = "0.11.0"
googleApiServicesDrive = "v3-rev20250829-2.0.0"
jiebaAnalysis = "1.0.3"
kotlin = "2.2.20"
compose = "1.8.2"
kotlinxDatetime = "0.7.1-0.6.x-compat"
kotlinxSerializationJson = "1.9.0"
normalize = "1.2.0"
playServicesAuth = "21.4.0"
room = "2.8.0"
sqlite = "2.6.0"
kermit = "2.0.8"
compose_ui = "1.9.1"
test_runner = "1.7.0"
test_junit_ext = "1.3.0"
ksp = "2.2.10-2.0.2"
textRecognitionChinese = "16.0.1"
ui = "1.8.2"
androidx-viewmodel = "2.9.4"
billingKtx = "8.0.0"
reviewKtx = "2.0.2"
workRuntimeKtxVersion = "2.10.4"
documentfile = "1.1.0"

[libraries]
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastorePreferences" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-viewmodel" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-viewmodel" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-viewmodel" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtxVersion" }
anki-android = { module = "com.github.ankidroid:Anki-Android", version.ref = "ankiAndroid" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekitCore" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekitCore" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekitCore" }
google-api-services-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiServicesDrive" }
camerak-imagesaver = { module = "io.github.kashif-mehmood-km:image_saver_plugin", version.ref = "camerak-imagesaver" }
jieba-analysis = { module = "io.github.yrjyrj123:jieba-analysis", version.ref = "jiebaAnalysis" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose_ui" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
normalize = { module = "com.doist.x:normalize", version.ref = "normalize" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test_runner" }
androidx-test-core = { module = "androidx.test:core", version.ref = "test_runner" }
androidx-test-junit-ext = { module = "androidx.test.ext:junit", version.ref = "test_junit_ext" }
androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room" }
text-recognition-chinese = { module = "com.google.mlkit:text-recognition-chinese", version.ref = "textRecognitionChinese" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "ui" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-viewmodel" }
billing-ktx = { group = "com.android.billingclient", name = "billing-ktx", version.ref = "billingKtx" }
review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "reviewKtx" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }